### PR TITLE
Add container info to framework

### PR DESCRIPTION
**Pull request by yyrdl**

### CODE REVIEW

**Comment by yqwang-ms** [comment]
Thanks for the PR. :)

So, why do you need to add ContainerStatuses into TaskAttemptStatus?
They are already in PodStatus, and we can use Namespace, PodName and PodUID to locate it.

**Comment by yyrdl** [comment]
> Thanks for the PR. :)
> 
> So, why do you need to add ContainerStatuses into TaskAttemptStatus?
> They are already in PodStatus, and we can use Namespace, PodName and PodUID to locate it.

Thanks for reply ^ _＾　

 yeah ， I can locate it by pod when the framework is still running . But  after the framework is completed , the pod will be deleted by the frameworkcontroller, then we will lose the container information .

**Comment by yqwang-ms** [comment]
Yep, this is by design as we have no other choice to stop a running Pod except for deleting it.
But, we only store necessary info about the pod into TaskAttemptStatus, such as pod uid, etc, to store more history info, we plan to store them into a history store, such as a DB, instead of into TaskAttemptStatus which will be eventually stored in ETCD, which is not designed to store too much history data.

**Comment by yyrdl** [comment]
> Yep, this is by design as we have no other choice to stop a running Pod except for deleting it.
> But, we only store necessary info about the pod into TaskAttemptStatus, such as pod uid, etc, to store more history info, we plan to store them into a history store, such as a DB, instead of into TaskAttemptStatus which will be eventually stored in ETCD, which is not designed to store too much history data.

You are right , it is not a good choice to store too many things in ETCD , we store the whole information (config , status , resource usage etc..) of a framework in mysql . When the framework is completed , we will also delete the framework from k8s in rest-server.  

In my company , we need to supply the container log to user, then container information is necessary. If we can get the container info  from TaskAttemptStatus  directly , it will be more convenient. Otherwise , we need to sync the info when it is changed ( created , recreated ...), which is complex .

Besides, we also need "container id "  and "node ip"   to supply  "docker commit" feature.

This PR is just a suggestion  :)

**Comment by yqwang-ms** [comment]
First thanks to try out the frameworkcontroller :)
We (https://github.com/Microsoft/pai) are also trying to leverage frameworkcontroller to provide a pure k8s PAI in next few months. We also face the same Framework Status History and Container Log problem.
Even though we have not decided the final design, but you can try below options:
1. Framework Status History
If Framework Status changed (such as Task retried with a new Pod), push it into another store, like DB or just local file system.
You can also have a history web server to serve these history status.

2. Container Log 
Each container can write its log to a distributed FS, like HDFS or NFS, with path like:
`/logs/$FRAMEWORK_NAME/$FRAMEWORK_ATTEMPT_ID/$TASKROLE_NAME/$TASK_INDEX/$TASK_ATTEMPT_ID/$CONTAINER_NAME/***`
Or
`/logs/$FRAMEWORK_NAME/$FRAMEWORK_ATTEMPT_ID/$TASKROLE_NAME/$TASK_INDEX/$TASK_ATTEMPT_ID/$CONTAINER_NAME/$NODE_IP/$CONTAINER_ID/***`
You can also have a log web server to serve these logs.

It seems that 2 can already solve this

> In my company , we need to supply the container log to user, then container information is necessary. If we can get the container info from TaskAttemptStatus directly , it will be more convenient. Otherwise , we need to sync the info when it is changed ( created , recreated ...), which is complex .

Anyway to solve all things, we need both 1 and 2.

**Comment by yyrdl** [comment]
yep ,  it's just a suggestion , we will be happy to see your  final design  :)

**Comment by yqwang-ms** [comment]
Thanks for the understanding, will notify you for the final design. 
Currently, you can continue use your own apporach in the PR, I will close it now, and reopen it later on demand.

**Comment by yqwang-ms** [comment]
Hi @yyrdl , please check our final design:
1. PR https://github.com/microsoft/frameworkcontroller/pull/31 will let FC to expose pod (and framework) history.
2. We plan to use EFK to collect the pod (and framework) history in https://github.com/Microsoft/pai. 
You can also do this by yourself.

**Comment by yyrdl** [comment]
> Hi @yyrdl , please check our final design:
> 
> 1. PR #31 will let FC to expose pod (and framework) history.
> 2. We plan to use EFK to collect the pod (and framework) history in https://github.com/Microsoft/pai.
>    You can also do this by yourself.
> 
> Any comments? :)

哈哈，谢谢提醒，这样确实解决了问题，挺好的 :+1:

**Comment by yqwang-ms** [comment]
:handshake:

**Comment by yqwang-ms** [comment]
Refer example for job/pod history in:
https://github.com/microsoft/pai/pull/3626

**Comment by yyrdl** [comment]
> @yyrdl pls refer example for job/pod history in:
> [microsoft/pai#3626](https://github.com/microsoft/pai/pull/3626)
> [microsoft/pai#3623](https://github.com/microsoft/pai/pull/3623)

:) thanks

**Pull request closed without merging**
